/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpc3Rhbi9EZXNrdG9wL0FuZ3VsYXIgZnJvbSBCZWdpbm5lciB0byBBZHZhbmNlZC9EZXBsb3ltZW50L3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9UcmlzdGFuL0Rlc2t0b3AvQW5ndWxhciBmcm9tIEJlZ2lubmVyIHRvIEFkdmFuY2VkL0RlcGxveW1lbnQvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
