/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpc3Rhbi9EZXNrdG9wL0FuZ3VsYXIgZnJvbSBCZWdpbm5lciB0byBBZHZhbmNlZC9EZXBsb3ltZW50L3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL1RyaXN0YW4vRGVza3RvcC9Bbmd1bGFyIGZyb20gQmVnaW5uZXIgdG8gQWR2YW5jZWQvRGVwbG95bWVudC9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
