/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVHJpc3Rhbi9EZXNrdG9wL0FuZ3VsYXIgZnJvbSBCZWdpbm5lciB0byBBZHZhbmNlZC9EZXBsb3ltZW50L3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvVHJpc3Rhbi9EZXNrdG9wL0FuZ3VsYXIgZnJvbSBCZWdpbm5lciB0byBBZHZhbmNlZC9EZXBsb3ltZW50L3NyYy9hcHAvaG9tZS9ob21lLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
